model:
  model_name: "EleutherAI/pythia-14m"
  tokenizer_name: "EleutherAI/pythia-14m"
  tokenizer_pad_token: ' '
  model_max_length: 512
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "allenai/tulu-3-sft-mixture"
    target_col: "prompt"

training:
  trainer_type: TRL_SFT
  save_final_model: True
  save_steps: 100
  max_steps: 10
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4

  ddp_find_unused_parameters: False
  optimizer: "adamw_torch"
  learning_rate: 5.0e-06
  compile: False

  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32

  logging_steps: 1
  log_model_summary: False
  empty_device_cache_steps: 50
  output_dir: "output/mini_tulu3"
  include_performance_metrics: True
